"""Bootstrap/verify the AION Checkpoint Mestre runtime document.

This script performs no network I/O. It only generates or validates a local
checkpoint document using the same canonical normalization/integrity logic as
the application. GitHub Actions may then persist the generated bytes to the
dedicated runtime branch.

Safety:
- real trading remains disabled;
- output is a clean canonical checkpoint;
- verification fails closed on digest mismatch or unsafe version;
- no secret is written into the checkpoint.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from atlasquant_aion_memory import (
    checkpoint_integrity_report,
    checkpoint_source_digest,
    default_checkpoint,
    ensure_operating_checkpoint,
)


def canonical_bootstrap_checkpoint() -> dict[str, Any]:
    payload = ensure_operating_checkpoint(default_checkpoint())
    payload["operating"]["dirty"] = False
    payload["aion"]["real_trading"] = False
    return payload


def write_checkpoint(path: str | Path) -> dict[str, Any]:
    target = Path(path)
    payload = canonical_bootstrap_checkpoint()
    integrity = checkpoint_integrity_report(payload)
    if integrity.get("state") != "CONFIRMED":
        raise ValueError(f"bootstrap integrity not confirmed: {integrity.get('state')}")
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True, default=str) + "\n",
        encoding="utf-8",
    )
    return {
        "status": "CONFIRMED",
        "path": str(target),
        "checkpoint_version": int(payload.get("checkpoint_version") or 0),
        "digest": checkpoint_source_digest(payload),
        "real_trading": bool(payload.get("aion", {}).get("real_trading", False)),
    }


def verify_checkpoint(path: str | Path) -> dict[str, Any]:
    target = Path(path)
    payload = json.loads(target.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError("checkpoint must be a JSON object")
    integrity = checkpoint_integrity_report(payload)
    if integrity.get("state") != "CONFIRMED":
        raise ValueError(f"checkpoint integrity not confirmed: {integrity.get('state')}")
    normalized = ensure_operating_checkpoint(payload)
    version = int(normalized.get("checkpoint_version") or 0)
    if version < 13:
        raise ValueError("checkpoint version is older than V13")
    if bool(normalized.get("aion", {}).get("real_trading", False)):
        raise ValueError("real trading must remain disabled")
    return {
        "status": "CONFIRMED",
        "path": str(target),
        "checkpoint_version": version,
        "digest": checkpoint_source_digest(normalized),
        "real_trading": False,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--output")
    group.add_argument("--verify")
    args = parser.parse_args()
    result = write_checkpoint(args.output) if args.output else verify_checkpoint(args.verify)
    print(json.dumps(result, ensure_ascii=False, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
