plugins {
    id "com.android.application"
}

android {
    namespace "com.atlasquant.mobile"
    compileSdk 35

    defaultConfig {
        applicationId "com.atlasquant.mobile"
        minSdk 26
        targetSdk 35
        versionCode 2
        versionName "0.2"
    }

    buildTypes {
        debug {
            applicationIdSuffix ".test"
            versionNameSuffix "-test"
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
